"""primeira carga

Revision ID: 4c68cd4fe5c5
Revises: 
Create Date: 2025-12-14 20:20:32.415957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c68cd4fe5c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_CBOEntidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tb_CBOEntidade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tb_CBOEntidade_titulo'), ['titulo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_CBOEntidade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tb_CBOEntidade_titulo'))

    op.drop_table('tb_CBOEntidade')
    # ### end Alembic commands ###
